name: "Check README and text"

on:
  push:
    paths:
      - '**/*.md'
      - '**/words.dic'

  pull_request:
    paths:
      - '**/*.md'
      - '**/words.dic'

jobs:
  MDSpelling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prerrequisites
        run:   make prespell
      - name: Spell check
        run: make spellcheck
