name: "Check README and text"

on:
  push:
    paths:
      - '**/*.md'
      - '**/words.dic'

  pull_request:
    paths:
      - '**/*.md'
      - '**/words.dic'

jobs:
  MDSpelling:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: |
          make prespell
      - uses: actions/checkout@v2
      - name: Usa install-with-cpm
        uses: perl-actions/install-with-cpm@stable
        with:
          install: |
            Test::Text
            TAP::Harness
          sudo: true
      - name: Spell check
        run: |
          make spellcheck
