name: "Check README and text"

on:
  push:
    paths:
      - '**/*.md'
      - '**/words.dic'

  pull_request:
    paths:
      - '**/*.md'
      - '**/words.dic'

jobs:
  MDSpelling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prerrequisites
        run:   make prespell
      - name: Spell check
        run: make spellcheck
      - name: Install pandoc
        run: sudo apt-get -y install pandoc
      - name: Generate pages
        run: bin/md2html
      - name: Check in result
        run: git config --global user.email 'jjmerelo@gmail.com' && git config --global user.name "MLoPS bot" && git commit -am "Re-generated HTML" && git push
