name: "Check README and text"

on:
  push:
    paths:
      - 'README.md'
      - 'words.dic'

  pull_request:
    paths:
      - 'README.md'
      - 'words.dic'

jobs:
  MDSpelling:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: |
          sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y libtext-hunspell-perl
      - uses: actions/checkout@v2
      - name: Usa install-with-cpm
        uses: perl-actions/install-with-cpm@stable
        with:
          install: |
            Test::Text
            TAP::Harness
          sudo: true
      - name: Spell check
        run: |
          curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/en_US.aff -o English.aff
          curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/en_US.dic -o English.dic
          echo "use Test::Text; just_check( '.','.', 'English',0 );use Test::Text; just_check( 'text','.', 'English' );  " > just_check.t
          perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if $harness->runtests( "just_check.t" )->failed;'
