name: "Tests perl with system one"
on:
  push:
    paths:
      - "code/perl/**"
      - '.github/workflows/perl.yml'
  pull_request:
    paths:
      - "code/perl/**"

jobs:
  check_perl_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install prerrequisites as system modules
        run: sudo cpan Module::Build Test::Perl::Critic Test::Pod::Coverage
      - name: Build
        working-directory: code/perl
        run: |
          perl Build.PL
          ./Build test
